# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-25 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=60, unique=True, verbose_name='bairro')),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
                'db_table': 'educacao_vagas_bairro_responsavel',
            },
        ),
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_crianca', models.CharField(max_length=80, verbose_name='Nome da criança')),
                ('dt_nascimento', models.DateField(verbose_name='Data de nascimento')),
            ],
            options={
                'verbose_name': 'Criança',
                'verbose_name_plural': 'Crianças',
                'db_table': 'educacao_vagas_crianca',
            },
        ),
        migrations.CreateModel(
            name='EnderecoCrianca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complemento', models.CharField(blank=True, max_length=80, null=True, verbose_name='complemento')),
                ('numero', models.CharField(max_length=30, verbose_name='número')),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bairros_criancas', to='educacao_vagas.Bairro')),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criancas_enderecos', to='educacao_vagas.Crianca')),
            ],
            options={
                'verbose_name': 'Logradouro criança',
                'db_table': 'educacao_endereco_crianca',
            },
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_escola', models.CharField(max_length=100, verbose_name='Escola')),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
                'db_table': 'educacao_vagas_escola',
            },
        ),
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=80, unique=True, verbose_name='Logradouro')),
            ],
            options={
                'verbose_name': 'Logradouro',
                'verbose_name_plural': 'Logradouros',
                'db_table': 'educacao_vagas_endereco',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(max_length=80, verbose_name='Responsável')),
                ('rg_responsavel', models.CharField(max_length=14, verbose_name='RG')),
                ('telefone', models.CharField(max_length=60, verbose_name='Telefone(s)')),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
                'db_table': 'educacao_vagas_responsavel',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoAtendida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_atendimento', models.DateTimeField(auto_now=True, verbose_name='data de atendimento')),
                ('observacao', models.TextField(verbose_name='observação')),
            ],
            options={
                'verbose_name': 'Solicitação atendida',
                'verbose_name_plural': 'Atendimento solicitação',
                'db_table': 'educacao_atendimento_solicitacao_vagas',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoVaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Aguardando vaga'), (2, 'Sem contato/Não compareceu após contato'), (3, 'Aguardando vaga para transferência'), (4, 'Atendido')], verbose_name='status')),
                ('dt_solicitacao', models.DateField(verbose_name='Data da solicitação')),
                ('observacao', models.TextField(max_length=4000, verbose_name='Observação')),
                ('dt_alteracao', models.DateTimeField(auto_now=True, verbose_name='data alteração')),
                ('atendida_flag', models.BooleanField(default=False, verbose_name='atendida flag')),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criancas', to='educacao_vagas.Crianca')),
            ],
            options={
                'verbose_name': 'Solicitação vaga',
                'verbose_name_plural': 'Solicitações vagas',
                'db_table': 'educacao_vagas_solicitacao',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_turma', models.CharField(max_length=80, verbose_name='turma')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escolas', to='educacao_vagas.Escola')),
            ],
            options={
                'verbose_name': 'Turma/Escola',
                'verbose_name_plural': 'Turmas/Escolas',
                'db_table': 'educacao_vagas_turma_escola',
            },
        ),
        migrations.AddField(
            model_name='solicitacaovaga',
            name='turma_preferencia',
            field=models.ManyToManyField(related_name='turmas', to='educacao_vagas.Turma'),
        ),
        migrations.AddField(
            model_name='solicitacaoatendida',
            name='solicitacao',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='educacao_vagas.SolicitacaoVaga'),
        ),
        migrations.AddField(
            model_name='solicitacaoatendida',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educacao_vagas.Turma'),
        ),
        migrations.AddField(
            model_name='enderecocrianca',
            name='logradouro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logradouros_criancas', to='educacao_vagas.Logradouro'),
        ),
        migrations.AddField(
            model_name='crianca',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='educacao_vagas.Responsavel'),
        ),
    ]
