# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-25 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao_vagas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaovaga',
            name='dt_solicitacao',
            field=models.DateTimeField(verbose_name='Data da solicitação'),
        ),
    ]
