# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-13 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaatracao',
            name='descricao',
            field=models.CharField(default='', max_length=80, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='categoriaatracao',
            name='tipo',
            field=models.CharField(max_length=80, verbose_name='tipo'),
        ),
    ]
