# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-08 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioOficial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='numero')),
                ('ano', models.CharField(max_length=4, verbose_name='ano')),
                ('mes', models.CharField(choices=[('janeiro', 'janeiro'), ('fevereiro', 'fevereiro'), ('marco', 'março'), ('abril', 'abril'), ('maio', 'maio'), ('junho', 'junho'), ('julho', 'julho'), ('agosto', 'agosto'), ('setembro', 'setembro'), ('outubro', 'outubro'), ('novembro', 'novembro'), ('dezembro', 'dezembro')], max_length=15, verbose_name='mês')),
                ('arquivo', filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Arquivo')),
                ('publicacao', models.DateField(verbose_name='publicação')),
            ],
            options={
                'verbose_name': 'Diário Oficial',
                'verbose_name_plural': 'Diário Oficial',
                'db_table': 'tb_diario_oficial',
            },
        ),
    ]
