# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-08 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario_oficial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diariooficial',
            name='ano',
            field=models.IntegerField(max_length=4, verbose_name='ano'),
        ),
    ]
