# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-08 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario_oficial', '0002_auto_20170808_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diariooficial',
            name='ano',
            field=models.IntegerField(verbose_name='ano'),
        ),
    ]
