# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('diario_oficial', '0003_auto_20170808_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioOficialExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('arquivo', filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='PDF')),
                ('publicacao', models.DateTimeField(auto_now_add=True, verbose_name='publicação')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diarios', to='diario_oficial.DiarioOficial')),
            ],
            options={
                'verbose_name': 'Diario Oficial Arquivo Extra',
                'verbose_name_plural': 'Diario Oficial Arquivos Extras',
                'db_table': 'tb_diario_extra_licitacao',
            },
        ),
    ]
