# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario_oficial', '0004_diariooficialextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='diariooficial',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'EDIÇÃO REGULAR'), (2, 'EDIÇÃO EXTRA')], default=1, verbose_name='Tipo de Diario'),
        ),
    ]
