# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_oficial', '0005_diariooficial_tipo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiarioOficialExtra',
            new_name='DiarioOficialExtraArquivos',
        ),
        migrations.AlterModelTable(
            name='diariooficialextraarquivos',
            table='tb_diario_extra_arquivos',
        ),
    ]
