# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario_oficial', '0007_diariooficial_texto_arquivo_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diariooficial',
            old_name='texto_arquivo_pdf',
            new_name='texto_arquivo_diario',
        ),
    ]
