# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170310_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerhome',
            name='secao',
            field=models.CharField(choices=[('banner-principal', 'Banner principal'), ('banner_2', 'Banner  790x90'), ('banner_2_1', 'Banner  790x90 2'), ('banner_3', 'Banner 337x280'), ('banner_4', 'Banner 300x400')], max_length=20, verbose_name='seção'),
        ),
    ]
