# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170315_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoyoutube',
            name='url_externa',
            field=models.CharField(choices=[('sim', 'sim'), ('nao', 'não')], default='nao', max_length=3, verbose_name='url externa?'),
        ),
    ]
