# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_videoyoutube_url_externa'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerhome',
            name='secretaria',
            field=models.CharField(choices=[('gabinete', 'Gabinete'), ('administracao', 'Administração'), ('educacao', 'Educação'), ('infraestrutura', 'Infraestrutura'), ('social', 'Assistência Social'), ('saude', 'Saúde'), ('esportes', 'Esportes, Cultura e Turismo')], default='administracao', max_length=60, verbose_name='secretaria'),
        ),
        migrations.AddField(
            model_name='videoyoutube',
            name='secretaria',
            field=models.CharField(choices=[('gabinete', 'Gabinete'), ('administracao', 'Administração'), ('educacao', 'Educação'), ('infraestrutura', 'Infraestrutura'), ('social', 'Assistência Social'), ('saude', 'Saúde'), ('esportes', 'Esportes, Cultura e Turismo')], default='administracao', max_length=60, verbose_name='secretaria'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='secretaria',
            field=models.CharField(choices=[('gabinete', 'Gabinete'), ('administracao', 'Administração'), ('educacao', 'Educação'), ('infraestrutura', 'Infraestrutura'), ('social', 'Assistência Social'), ('saude', 'Saúde'), ('esportes', 'Esportes, Cultura e Turismo')], default='administracao', max_length=60, verbose_name='secretaria'),
        ),
    ]
