# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170411_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerhome',
            name='secao',
            field=models.CharField(choices=[('banner_principal', 'Banner principal'), ('banner_729x90', 'Banner  729x90'), ('banner_729x90_1', 'Banner  729x90 2'), ('banner_337x280', 'Banner 337x280'), ('banner_300x400', 'Banner 300x400'), ('banner_729x90_footer', 'Banner 729x90 footer')], max_length=20, verbose_name='seção'),
        ),
    ]
