# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 18:00
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_noticia_legenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoyoutube',
            name='embed',
            field=embed_video.fields.EmbedVideoField(default='https://www.youtube.com/watch?v=7pLRCc-b8dg', verbose_name='embed video youtube'),
        ),
    ]
