# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 18:16
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170523_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoyoutube',
            name='embed',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='embed'),
        ),
    ]
