# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20170530_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoyoutube',
            name='url',
            field=models.URLField(blank=True, max_length=80, null=True, verbose_name='url do video'),
        ),
        migrations.AlterField(
            model_name='videoyoutube',
            name='url_externa',
            field=models.CharField(blank=True, choices=[('sim', 'sim'), ('nao', 'não')], max_length=3, null=True, verbose_name='url externa?'),
        ),
    ]
