# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20170815_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='resumo',
            field=models.CharField(blank=True, max_length=250, verbose_name='resumo'),
        ),
    ]
