# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-30 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crianca', '0002_remove_crianca_georginaissa'),
    ]

    operations = [
        migrations.AddField(
            model_name='crianca',
            name='Issa',
            field=models.BooleanField(default=False, verbose_name='Vaga para Georgina Issa?'),
        ),
        migrations.AddField(
            model_name='crianca',
            name='data_comparecimento_georgina',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Comparecimento Georgina Issa'),
        ),
        migrations.AddField(
            model_name='crianca',
            name='dt_nascimento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='crianca',
            name='posicao_issa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Posição do aluno no Georgina Issa'),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='status',
            field=models.CharField(blank=True, choices=[('ATENDIDA', 'Atendida'), ('SEM CONTATO', 'Sem Contato'), ('AGUARDANDO VAGA', 'Aguardando Vaga'), ('DESISTENTE/ABANDONO', 'Desistente/Abandono'), ('AGUARDANDO TRANSFERENCIA', 'Aguardando Transferência'), ('TRANFERIDO', 'Transferido')], max_length=20, null=True),
        ),
    ]
