# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivosLicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='descrição')),
                ('arquivo', filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='PDF')),
                ('publicacao', models.DateTimeField(auto_now_add=True, verbose_name='publicação')),
            ],
            options={
                'verbose_name': 'Arquivos licitacao',
                'verbose_name_plural': 'Arquivos Licitação',
                'db_table': 'tb_arquivos_licitacao',
            },
        ),
        migrations.CreateModel(
            name='Licitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300, verbose_name='descrição')),
                ('numero', models.IntegerField(verbose_name='numero')),
                ('ano', models.IntegerField(verbose_name='ano')),
                ('arquivos', models.ManyToManyField(to='licitacoes.ArquivosLicitacao')),
            ],
            options={
                'verbose_name': 'Licitação',
                'verbose_name_plural': 'Licitações',
                'db_table': 'tb_licitacao',
            },
        ),
        migrations.CreateModel(
            name='ModalidadeLicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=80, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'Modalidade Licitação',
                'verbose_name_plural': 'Modalidades licitação',
                'db_table': 'tb_modalidade_licitacao',
            },
        ),
        migrations.AddField(
            model_name='licitacao',
            name='modalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitacoes.ModalidadeLicitacao'),
        ),
    ]
