# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-28 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0002_auto_20170321_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivosconcurso',
            name='publicacao',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='data da publicação'),
        ),
    ]
