# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-28 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0003_auto_20180328_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arquivosconcurso',
            options={'ordering': ['-publicacao'], 'verbose_name': 'Arquivos Concrusos', 'verbose_name_plural': 'Arquivos concursos'},
        ),
    ]
