# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secretaria', models.CharField(choices=[('administracao', 'Administração e Finanças'), ('social', 'Assistencia Social'), ('educacao', 'Educação'), ('infra', 'Infraestrutura'), ('saude', 'Saúde'), ('esportes', 'Esportes, Cultura e Turismo'), ('gabinete', 'Gabinete do Prefeitu'), ('outros', 'Outros')], max_length=30, verbose_name='secretaria')),
                ('orgao', models.CharField(max_length=80, verbose_name='orgão')),
                ('endereco', models.CharField(max_length=80, verbose_name='endereço')),
                ('telefone', models.CharField(max_length=80, verbose_name='telefone(s)')),
                ('horario', models.TextField(verbose_name='horario de funcionamento')),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localização',
                'db_table': 'tb_localizacao_orgaos',
                'ordering': ['orgao'],
            },
        ),
        migrations.CreateModel(
            name='LocalizacaoBairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=60, unique=True, verbose_name='bairro')),
            ],
            options={
                'verbose_name': 'Localização Bairro',
                'verbose_name_plural': 'Localização Bairros',
                'db_table': 'tb_localizacao_bairro',
                'ordering': ['bairro'],
            },
        ),
        migrations.AddField(
            model_name='localizacao',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizacao_orgaos.LocalizacaoBairro'),
        ),
    ]
