# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import filebrowser.fields
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='título')),
                ('imagem', filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='imagem')),
                ('publicacao', models.DateTimeField(auto_now_add=True, verbose_name='publicação')),
            ],
            options={
                'verbose_name': 'Foto galeria',
                'verbose_name_plural': 'Fotos galerias',
                'db_table': 'tb_foto_galeria',
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80, verbose_name='título')),
                ('publicacao', models.DateTimeField(auto_now_add=True, verbose_name='publicação')),
                ('fotos', sortedm2m.fields.SortedManyToManyField(help_text=None, to='galeria.FotoGaleria')),
            ],
            options={
                'verbose_name': 'galeria',
                'verbose_name_plural': 'galerias',
                'db_table': 'tb_galeria',
            },
        ),
    ]
