# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 19:13
from __future__ import unicode_literals

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeria',
            old_name='fotos',
            new_name='imagens',
        ),
        migrations.AlterField(
            model_name='fotogaleria',
            name='imagem',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True),
        ),
    ]
