# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_auto_20170309_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotogaleria',
            options={'ordering': ('-publicacao',), 'verbose_name': 'Foto galeria', 'verbose_name_plural': 'Fotos galerias'},
        ),
        migrations.AddField(
            model_name='galeria',
            name='secao',
            field=models.CharField(choices=[('galeria1', 'Galeria 1'), ('galeria2', 'Galeria 2')], default='galeria1', max_length=11, verbose_name='galeria de imagens'),
        ),
    ]
