# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 18:39
from __future__ import unicode_literals

from django.db import migrations
import thumbnail_maker.fields


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_auto_20170310_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotogaleria',
            name='imagem',
            field=thumbnail_maker.fields.ImageWithThumbnailsField(blank=True, null=True, upload_to='galerias/'),
        ),
    ]
