# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_auto_20170407_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='secretaria',
            field=models.CharField(choices=[('gabinete', 'Gabinete'), ('administracao', 'Administração'), ('educacao', 'Educação'), ('infraestrutura', 'Infraestrutura'), ('social', 'Assistência Social'), ('saude', 'Saúde'), ('esportes', 'Esportes, Cultura e Turismo')], default='administracao', max_length=60, verbose_name='secretaria'),
        ),
    ]
