# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_galeria_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeria',
            options={'ordering': ('-publicacao',), 'verbose_name': 'galeria', 'verbose_name_plural': 'galerias'},
        ),
    ]
