# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_auto_20170731_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='slug',
            field=models.SlugField(blank=True, max_length=80, null=True, verbose_name='URL (slug)'),
        ),
    ]
