# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-13 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atracao', models.CharField(max_length=180, verbose_name='atração')),
                ('descricao', models.TextField(max_length=4000, verbose_name='descricao')),
                ('imagem', models.ImageField(upload_to='uploads/turismo', verbose_name='imagem')),
            ],
            options={
                'verbose_name': 'Atração',
                'verbose_name_plural': 'Atrações',
                'db_table': 'tb_turismo_atracao',
            },
        ),
        migrations.CreateModel(
            name='CategoriaAtracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=60, verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'tb_turismo_categoria',
            },
        ),
        migrations.AddField(
            model_name='atracao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atracoes', to='turismo.CategoriaAtracao'),
        ),
    ]
