# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-13 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0002_auto_20180313_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaatracao',
            name='tipo',
        ),
        migrations.AddField(
            model_name='categoriaatracao',
            name='tag',
            field=models.CharField(default='', max_length=80, verbose_name='tag'),
        ),
    ]
