# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-13 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0003_auto_20180313_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaatracao',
            name='descricao',
            field=models.CharField(max_length=80, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='categoriaatracao',
            name='tag',
            field=models.CharField(max_length=80, verbose_name='tag'),
        ),
    ]
