# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-16 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0005_auto_20180313_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180, verbose_name='nome')),
                ('descricao', models.TextField(max_length=4000, verbose_name='descrição')),
                ('imagem', models.ImageField(upload_to='uploads/turismo/pontos', verbose_name='imagem')),
            ],
            options={
                'verbose_name': 'Ponto Turistico',
                'verbose_name_plural': 'Pontos Turisticos',
                'db_table': 'tb_turismo_ponto_turistico',
            },
        ),
    ]
