# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-16 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0006_pontoturistico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='descricao',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='descrição'),
        ),
    ]
