# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaudeEscala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=120, verbose_name='Unidade')),
                ('endereco', models.CharField(max_length=120, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=60, verbose_name='Telefone(s)')),
                ('horario_funcionamento', models.CharField(max_length=80, verbose_name='Horário de Funcionamento')),
                ('arquivo', filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='PDF')),
                ('dt_atualizacao', models.DateField(verbose_name='Data de Inclusão')),
            ],
            options={
                'verbose_name': 'Saúde Escala',
                'verbose_name_plural': 'Saúde Escalas',
                'db_table': 'tb_saude_escala',
                'ordering': ['unidade'],
            },
        ),
        migrations.CreateModel(
            name='SaudeMedicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='PDF')),
                ('dt_atualizacao', models.DateField(verbose_name='Data de Inclusão')),
            ],
            options={
                'verbose_name_plural': 'Saude medicamentos',
                'db_table': 'tb_saude_medicamentos',
            },
        ),
    ]
