# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria_saude', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saudemedicamento',
            name='dt_atualizacao',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Inclusão'),
        ),
    ]
