# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria_saude', '0002_auto_20170413_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='saudemedicamento',
            name='nome_arquivo',
            field=models.CharField(default='padronizado', max_length=250, verbose_name='nome_arquivo'),
        ),
    ]
