# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria_saude', '0003_saudemedicamento_nome_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='saudemedicamento',
            name='status',
            field=models.CharField(choices=[('faltante', 'Faltantes'), ('em_estoque', 'Em estoque')], default='em_estoque', max_length=50, verbose_name='STATUS'),
        ),
    ]
