# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria_saude', '0004_saudemedicamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saudemedicamento',
            name='dt_atualizacao',
            field=models.DateField(auto_now=True, verbose_name='Data de Inclusão'),
        ),
    ]
