# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmendaParlamentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deputado', models.CharField(max_length=80, verbose_name='deputado')),
                ('foto', filebrowser.fields.FileBrowseField(blank=True, max_length=80, null=True, verbose_name='foto deputado')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL (slug)')),
                ('valor', models.CharField(max_length=80, verbose_name='valor')),
                ('destino', models.TextField(max_length=255, verbose_name='destino')),
                ('publicacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publicação')),
                ('intermediador', models.CharField(blank=True, max_length=80, null=True, verbose_name='intermediador')),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Emendas',
                'verbose_name_plural': 'Emendas',
                'db_table': 'tb_emenda_parlamentares',
                'ordering': ['-publicacao'],
                'get_latest_by': '-publicacao',
            },
        ),
    ]
