# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerhome',
            name='secao',
            field=models.CharField(choices=[('banner-principal', 'Banner principal'), ('banner_2', 'Banner  790x90'), ('banner_3', 'Banner 337x280'), ('banner_4', 'Banner 300x400')], max_length=20, verbose_name='seção'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='secao',
            field=models.CharField(choices=[('not_destaque_1', 'Destaque 1'), ('not_destaque_2', 'Destaque 2'), ('not_secretarias', 'Secretarias'), ('not_antigas1', 'Antigas seção 1'), ('not_antigas2', 'Antigas seção 2'), ('not_antigas3', 'Antigas seção 3'), ('veja_tambem', 'Veja também')], max_length=20, verbose_name='seção'),
        ),
    ]
