# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170313_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerhome',
            name='secao',
            field=models.CharField(choices=[('banner_principal', 'Banner principal'), ('banner_790x90', 'Banner  790x90'), ('banner_790x90_1', 'Banner  790x90 2'), ('banner_337x280', 'Banner 337x280'), ('banner_300x400', 'Banner 300x400')], max_length=20, verbose_name='seção'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='secao',
            field=models.CharField(choices=[('ultimas_noticias', 'Últimas noticias'), ('not_destaque_1', 'Destaque 1'), ('not_destaque_2', 'Destaque 2'), ('not_secretarias', 'Secretarias'), ('not_antigas1', 'Antigas seção 1'), ('not_antigas2', 'Antigas seção 2'), ('not_antigas3', 'Antigas seção 3'), ('veja_tambem', 'Veja também')], max_length=20, verbose_name='seção'),
        ),
    ]
