# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170510_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='legenda',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='legenda imagem'),
        ),
    ]
