# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170523_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoyoutube',
            name='embed',
            field=models.TextField(blank=True, null=True, verbose_name='código embed video youtube'),
        ),
    ]
