# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20170530_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoyoutube',
            name='titulo',
            field=models.CharField(max_length=250, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='videoyoutube',
            name='url_externa',
            field=models.CharField(choices=[('sim', 'sim'), ('nao', 'não')], default='nao', max_length=3, verbose_name='url externa?'),
        ),
    ]
