# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 18:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=6)),
                ('tipo_lei', models.CharField(choices=[('complementar', 'Lei complementar'), ('ordinaria', 'Lei ordinária'), ('decreto', 'Decreto'), ('portaria', 'Portaria'), ('convenio', 'Convênios Municipais')], max_length=15, verbose_name='Tipo do documento')),
                ('ano', models.CharField(max_length=4)),
                ('titulo', models.TextField()),
                ('arquivo', filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Arquivo PDF')),
                ('publicacao', models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 15, 18, 26, 25, 312625, tzinfo=utc), verbose_name='publicação')),
            ],
            options={
                'verbose_name': 'Lei',
                'verbose_name_plural': 'Leis',
                'db_table': 'tb_lei',
            },
        ),
    ]
