# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lei',
            name='publicacao',
            field=models.DateTimeField(auto_now=True, verbose_name='publicação'),
        ),
    ]
