# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leis', '0004_auto_20170530_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lei',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
