# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leis', '0005_auto_20170530_1620'),
        ('leis', '0004_auto_20170530_1315'),
    ]

    operations = [
    ]
